### ISSUE TITLE
stop reading from queue until asynchronous fetch finishes

### ISSUE THREAD

**Issue by mezod** [JBlaak/Redux-Queue#7]
Hey, I have a debounced fetch of data that may overwrite any actions in the frontend that modify the state between when the fetch is called and it returns. Generally, I'd handle this with setting an "isFetching" to true in the state and displaying a spinner, so that users can't make actions. However, this fetch is about synchronizing data and not requested by the user with any specific action. In other words, the user wouldn't expect the spinner at all. 

Because of that, I want to use a queue to enqueue all those actions the user takes between the asynchronous fetch is called and it finishes. I've read the docs here but I'm not entirely sure this lib does what I need. First, I just want to enqueue these actions in a very specific case, and not every time they execute. (I am not sure if wrapping the reducers in Queue makes it always wait) And second, in your example, you pass the parent action in the "children" action. How to go about this when the dispatches of actions come from different functions in different components? (especially when it can be several action types)

**Comment by JBlaak** [comment]
Hi, what I do in my projects is to keep track of a separate request-queue so that the actual server interaction is in the correct order after which I use this library to "inject" the responses. This should be a separate place in your app, it can just be a singleton managed somewhere outside of the Redux scope.

The queuing/injection of a result of an action only takes place when `queued: true`, so if there is an indication you can just toggle that flag and indicate to the lib that a request should be queued. 

About your question on how to cope with the `parent` when you create a child action in a different place. This is currently not possible, we could add something like an identifier to an action so we can reference it, but then you should know this identifier in the different places. Do you have a suggestion how that would work for you?

**Comment by mezod** [comment]
Honestly, I don't understand well enough how this lib works to suggest anything. I'm not even sure what's the use case, in which scenario do you have two actions called from the same component that depend on each other?
